apiVersion: v1
kind: Service
metadata:
  name: metabase-nova
  labels:
    app: metabase
spec:
  type: ClusterIP
  selector:
    app: metabase
  ports:
    - name: http
      port: 80
      targetPort: http
